#pragma once

constexpr auto PRINT_FUNC =
		"\nprint_int:\n"
		"\tpush rbp\n"
		"\tmov rbp, rsp\n"
		"\tsub rsp, 64\n"
		"\tmov rax, rdi\n"
		"\tmov [rbp - 64], rdi\n"
		"\tlea rsi, [rbp - 1]\n"
		"\tmov byte [rsi], 10\n"
		"\tmov rcx, 1\n"
		"\ttest rax, rax\n"
		"\tjne .convert\n"
		"\tdec rsi\n"
		"\tmov byte [rsi], '0'\n"
		"\tinc rcx\n"
		"\tjmp .write\n"
		".convert:\n"
		"\tmov r8, 10\n"
		".loop:\n"
		"\txor rdx, rdx\n"
		"\tdiv r8\n"
		"\tadd dl, '0'\n"
		"\tdec rsi\n"
		"\tmov [rsi], dl\n"
		"\tinc rcx\n"
		"\ttest rax, rax\n"
		"\tjne .loop\n"
		".write:\n"
		"\tmov rax, 0x2000004\n"
		"\tmov rdi, 1\n"
		"\tmov rdx, rcx\n"
		"\tsyscall\n"
		"\tmov rax, [rbp - 64]\n"
		"\tleave\n"
		"\tret\n";
